### ISSUE TITLE
Keyboard shortcut (ctlr+r) is not working 

### ISSUE THREAD

**Issue by dguay** [jimeh/zsh-peco-history#6] opened 2019-02-14 14:37 UTC
This plugin looks pretty good but I can't seem to make it work correctly. I have `peco` installed (on zsh) but when I hit ctlr+r, I get the default search `bck-i-search`. 

Calling `peco_select_history` does load the plugin but pressing enter on a command doesn't run it.

**Working on**
macOS 10.14.3
iTerm2 3.2.7
zsh 5.7.1

**Comment by cyruseuros** [comment] 2019-02-15 04:51
Exactly the same issue on Arch Linux

**Comment by cyruseuros** [comment] 2019-02-15 12:45
Alright, just make sure the plugin is loaded after compinit. If you're using zplug, just add `, defer:2` to the line where you load it.

**Comment by cyruseuros** [comment] 2019-02-15 12:50
That really should be in the docs.

**Comment by jimeh** [comment] 2019-02-15 12:58
Thanks for tracking down the cause of this issue @jjzmajic. I'll update the readme later today when I've got a bit more free time :)

**Comment by cyruseuros** [comment] 2019-02-15 18:34
Thanks for making the amazing plugin, `zsh-history-search-multi-word` never really played well with the rest of my config and was way too difficult to customize. Personal taste perhaps, but still a clear preference for me.

**Comment by dguay** [comment] 2019-02-15 19:11
@jjzmajic thanks it's working with zplug !

**Comment by jimeh** [comment] 2019-02-15 23:51
I've just updated the readme with `defer:2` for zplug, and basic description for the other installation methods. Hopefully should be good enough for others to avoid this issue in the future.

So I'll close this issue, but feel free to re-open it if you have any further problems.

**Closed as completed by jimeh** 2019-02-15 23:51 UTC
